"use strict";

module.exports.recommended = [
  {
    ruleId: "workspaces/require-dependency",
    severity: 2,
    message:
      "Importing from another workspace without listing it as a dependency is not allowed",
    line: 1,
    column: 1,
    nodeType: "CallExpression",
    messageId: "requireDependency",
    endLine: 1,
    endColumn: 18,
  },
  {
    ruleId: "workspaces/no-relative-imports",
    severity: 2,
    message: "Relative imports of other packages are not allowed",
    line: 2,
    column: 1,
    nodeType: "CallExpression",
    messageId: "noRelativeImports",
    endLine: 2,
    endColumn: 16,
    fix: {
      range: [28, 32],
      text: "@app/b",
    },
  },
  {
    ruleId: "workspaces/require-dependency",
    severity: 2,
    message:
      "Importing from another workspace without listing it as a dependency is not allowed",
    line: 2,
    column: 1,
    nodeType: "CallExpression",
    messageId: "requireDependency",
    endLine: 2,
    endColumn: 16,
  },
  {
    ruleId: "workspaces/no-absolute-imports",
    severity: 2,
    message: "Absolute imports within the current package are not allowed",
    line: 3,
    column: 1,
    nodeType: "CallExpression",
    messageId: "noAbsoluteImports",
    endLine: 3,
    endColumn: 18,
    fix: {
      range: [45, 51],
      text: ".",
    },
  },
];

module.exports.all = [
  {
    ruleId: "workspaces/require-dependency",
    severity: 2,
    message:
      "Importing from another workspace without listing it as a dependency is not allowed",
    line: 1,
    column: 1,
    nodeType: "CallExpression",
    messageId: "requireDependency",
    endLine: 1,
    endColumn: 18,
  },
  {
    ruleId: "workspaces/no-cross-imports",
    severity: 2,
    message: 'Import from package "@app/b" is not allowed',
    line: 1,
    column: 1,
    nodeType: "CallExpression",
    messageId: "noCrossImports",
    endLine: 1,
    endColumn: 18,
  },
  {
    ruleId: "workspaces/no-relative-imports",
    severity: 2,
    message: "Relative imports of other packages are not allowed",
    line: 2,
    column: 1,
    nodeType: "CallExpression",
    messageId: "noRelativeImports",
    endLine: 2,
    endColumn: 16,
    fix: {
      range: [28, 32],
      text: "@app/b",
    },
  },
  {
    ruleId: "workspaces/require-dependency",
    severity: 2,
    message:
      "Importing from another workspace without listing it as a dependency is not allowed",
    line: 2,
    column: 1,
    nodeType: "CallExpression",
    messageId: "requireDependency",
    endLine: 2,
    endColumn: 16,
  },
  {
    ruleId: "workspaces/no-cross-imports",
    severity: 2,
    message: 'Import from package "@app/b" is not allowed',
    line: 2,
    column: 1,
    nodeType: "CallExpression",
    messageId: "noCrossImports",
    endLine: 2,
    endColumn: 16,
  },
  {
    ruleId: "workspaces/no-absolute-imports",
    severity: 2,
    message: "Absolute imports within the current package are not allowed",
    line: 3,
    column: 1,
    nodeType: "CallExpression",
    messageId: "noAbsoluteImports",
    endLine: 3,
    endColumn: 18,
    fix: {
      range: [45, 51],
      text: ".",
    },
  },
];
